server:
  port: ${server.port}

management:
  security:
    flag: false
  server:
    port: ${management.port}
  metrics:
    export:
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: ${project.name}
  output:
    ansi:
      enabled: always
info:
  version: ${project.version}
  stage: dev

dominant:
  url: http://dominant:8022/v1/domain/repository
  networkTimeout: 3000

cache:
  maxSize: 100

scheduling:
  fixed:
    rate: 900000
